version: "2"

services:
  notebook:
    build: .
    image: base-notebook
    container_name: ${NAME}
    volumes:
     - "./work:/home/jovyan/work"
    ports:
      - "${PORT}:8888"

#volumes:
#  work:
#    external:
#      name: ${WORK_VOLUME}