version: "2"

services:
  notebook:
    build: .
    image: base-notebook
    container_name: ${NAME}
    volumes:
     - "workspace:/home/jovyan/workspace"
    ports:
      - "${PORT}:8888"
    environment:
      PASSWORD: "sha1:2e924f0c47aa:9409d80ce73c227365a09033df2632a05177df3e"

volumes:
  workspace:
    external:
      name: ${WORK_VOLUME}