version: "2"

services:
  notebook:
    build: ./ocr-docker/
    image: ocr-notebook
    container_name: ${NAME}
    volumes:
     - "work:/home/jovyan/work"
    ports:
      - "${PORT}:8888"

volumes:
  work:
    external:
      name: ${WORK_VOLUME}