# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: base-notebook
    container_name: ${NAME}
    volumes:
     - "workspace:/home/jupyter/workspace"
    ports:
      - "${PORT}:8888"
    environment:
      USE_HTTPS: "yes"
      PASSWORD: ${PASSWORD}

volumes:
  workspace:
    external:
      name: ${WORK_VOLUME}